/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Sun Dec  2 12:58:17 2018. */

#include "rgbledstatus.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t pb_RGBLedStatus_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, pb_RGBLedStatus, red, red, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, pb_RGBLedStatus, green, red, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, pb_RGBLedStatus, blue, green, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
