# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rgbledstatus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rgbledstatus.proto',
  package='pb',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x12rgbledstatus.proto\x12\x02pb\"8\n\x0cRGBLedStatus\x12\x0b\n\x03red\x18\x01 \x02(\x05\x12\r\n\x05green\x18\x02 \x02(\x05\x12\x0c\n\x04\x62lue\x18\x03 \x02(\x05')
)




_RGBLEDSTATUS = _descriptor.Descriptor(
  name='RGBLedStatus',
  full_name='pb.RGBLedStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='red', full_name='pb.RGBLedStatus.red', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='green', full_name='pb.RGBLedStatus.green', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blue', full_name='pb.RGBLedStatus.blue', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['RGBLedStatus'] = _RGBLEDSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RGBLedStatus = _reflection.GeneratedProtocolMessageType('RGBLedStatus', (_message.Message,), dict(
  DESCRIPTOR = _RGBLEDSTATUS,
  __module__ = 'rgbledstatus_pb2'
  # @@protoc_insertion_point(class_scope:pb.RGBLedStatus)
  ))
_sym_db.RegisterMessage(RGBLedStatus)


# @@protoc_insertion_point(module_scope)
