/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon Nov 26 11:37:24 2018. */

#include "sensorevent.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t pb_SensorEvent_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, pb_SensorEvent, deviceId, deviceId, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, pb_SensorEvent, timestamp, deviceId, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, pb_SensorEvent, humidity, timestamp, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, pb_SensorEvent, temperature, humidity, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
