# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensorevent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensorevent.proto',
  package='pb',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11sensorevent.proto\x12\x02pb\"Y\n\x0bSensorEvent\x12\x10\n\x08\x64\x65viceId\x18\x01 \x02(\x05\x12\x11\n\ttimestamp\x18\x02 \x02(\x05\x12\x10\n\x08humidity\x18\x03 \x02(\x02\x12\x13\n\x0btemperature\x18\x04 \x02(\x02')
)




_SENSOREVENT = _descriptor.Descriptor(
  name='SensorEvent',
  full_name='pb.SensorEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='pb.SensorEvent.deviceId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='pb.SensorEvent.timestamp', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='pb.SensorEvent.humidity', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='pb.SensorEvent.temperature', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['SensorEvent'] = _SENSOREVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorEvent = _reflection.GeneratedProtocolMessageType('SensorEvent', (_message.Message,), dict(
  DESCRIPTOR = _SENSOREVENT,
  __module__ = 'sensorevent_pb2'
  # @@protoc_insertion_point(class_scope:pb.SensorEvent)
  ))
_sym_db.RegisterMessage(SensorEvent)


# @@protoc_insertion_point(module_scope)
